

target 'MobileProvision_Example' do
  
  platform :ios, '8.0'
  pod 'MobileProvision', :path => '../'

end

target 'MobileProvisionCLI' do
  platform :macos, '10.10'
  pod 'MobileProvision', :path => '../'
  
end


